#!/usr/bin/env python3
"""Restore proper French accents in lib/l10n/app_fr.arb (UTF-8)."""

from __future__ import annotations

import json
import re
from pathlib import Path

ARB = Path(__file__).resolve().parents[1] / "lib" / "l10n" / "app_fr.arb"

WORD_MAP = {
    "Reinitialiser": "Réinitialiser",
    "Deverrouiller": "Déverrouiller",
    "parametres": "paramètres",
    "Parametres": "Paramètres",
    "parametre": "paramètre",
    "defini": "défini",
    "Defini": "Défini",
    "definitivement": "définitivement",
    "Media": "Média",
    "media": "média",
    "medias": "médias",
    "Medias": "Médias",
    "Echec": "Échec",
    "echec": "échec",
    "selection": "sélection",
    "Selection": "Sélection",
    "selectionner": "sélectionner",
    "Selectionner": "Sélectionner",
    "Selectionnez": "Sélectionnez",
    "selectionnez": "sélectionnez",
    "selectionne": "sélectionné",
    "Selectionne": "Sélectionné",
    "selectionnes": "sélectionnés",
    "Decouvrir": "Découvrir",
    "decouvrir": "découvrir",
    "Decouvrez": "Découvrez",
    "verrouilles": "verrouillés",
    "verrouille": "verrouillé",
    "Verrouille": "Verrouillé",
    "Francais": "Français",
    "systeme": "système",
    "Systeme": "Système",
    "Theme": "Thème",
    "utilisee": "utilisée",
    "utilisees": "utilisées",
    "utilise": "utilisé",
    "Utilise": "Utilisé",
    "utilises": "utilisés",
    "Previsualisez": "Prévisualisez",
    "Gerer": "Gérer",
    "gerer": "gérer",
    "Retention": "Rétention",
    "Elements": "Éléments",
    "elements": "éléments",
    "element": "élément",
    "Element": "Élément",
    "bibliotheque": "bibliothèque",
    "Bibliotheque": "Bibliothèque",
    "periode": "période",
    "periodes": "périodes",
    "fermee": "fermée",
    "ferme": "fermé",
    "efface": "effacé",
    "Efface": "Effacé",
    "Reanalyse": "Réanalyse",
    "preferences": "préférences",
    "preference": "préférence",
    "arriere-plan": "arrière-plan",
    "Acces": "Accès",
    "acces": "accès",
    "acceder": "accéder",
    "accorde": "accordé",
    "Accorde": "Accordé",
    "geolocalisee": "géolocalisée",
    "geolocalisees": "géolocalisées",
    "geolocalise": "géolocalisé",
    "Reessayez": "Réessayez",
    "reessayez": "réessayez",
    "Reessayer": "Réessayer",
    "apparaitront": "apparaîtront",
    "apparait": "apparaît",
    "Apparait": "Apparaît",
    "idees": "idées",
    "idee": "idée",
    "masque": "masqué",
    "Masque": "Masqué",
    "deplace": "déplacé",
    "Deplace": "Déplacé",
    "deplacer": "déplacer",
    "Deplacer": "Déplacer",
    "deplaces": "déplacés",
    "supprimes": "supprimés",
    "supprime": "supprimé",
    "Supprimes": "Supprimés",
    "apres": "après",
    "Apres": "Après",
    "etre": "être",
    "creee": "créée",
    "cree": "créé",
    "Cree": "Créé",
    "Creer": "Créer",
    "creer": "créer",
    "echouee": "échouée",
    "echoue": "échoué",
    "annulee": "annulée",
    "annule": "annulé",
    "securise": "sécurisé",
    "Securise": "Sécurisé",
    "visibilite": "visibilité",
    "Visibilite": "Visibilité",
    "derniere": "dernière",
    "Derniere": "Dernière",
    "dernieres": "dernières",
    "protege": "protégé",
    "proteges": "protégés",
    "protegees": "protégées",
    "biometrie": "biométrie",
    "Biometrie": "Biométrie",
    "Aleatoire": "Aléatoire",
    "aleatoire": "aléatoire",
    "Tres": "Très",
    "tres": "très",
    "Instantane": "Instantané",
    "instantane": "instantané",
    "economise": "économisé",
    "Economise": "Économisé",
    "Aimes": "Aimés",
    "aimes": "aimés",
    "Traites": "Traités",
    "traites": "traités",
    "termine": "terminé",
    "Termine": "Terminé",
    "genere": "généré",
    "Genere": "Généré",
    "generer": "générer",
    "controle": "contrôle",
    "Controle": "Contrôle",
    "numero": "numéro",
    "Numero": "Numéro",
    "memoire": "mémoire",
    "Memoire": "Mémoire",
    "qualite": "qualité",
    "Qualite": "Qualité",
    "deja": "déjà",
    "Deja": "Déjà",
    "egalement": "également",
    "egal": "égal",
    "Egal": "Égal",
    "evenement": "événement",
    "Evenement": "Événement",
    "telechargement": "téléchargement",
    "Telechargement": "Téléchargement",
    "telecharge": "téléchargé",
    "demarre": "démarré",
    "Demarre": "Démarré",
    "demarrer": "démarrer",
    "arrete": "arrêté",
    "Arrete": "Arrêté",
    "arreter": "arrêter",
    "Preparation": "Préparation",
    "preparation": "préparation",
    "donnees": "données",
    "Donnees": "Données",
    "donnee": "donnée",
    "apparaitre": "apparaître",
    "necessite": "nécessite",
    "Necessite": "Nécessite",
    "necessaire": "nécessaire",
    "affichee": "affichée",
    "affiche": "affiché",
    "Affiche": "Affiché",
    "Video": "Vidéo",
    "video": "vidéo",
    "videos": "vidéos",
    "Videos": "Vidéos",
    "conservees": "conservées",
    "conservee": "conservée",
    "conserves": "conservés",
    "conserve": "conservé",
    "Conserve": "Conservé",
    "indexees": "indexées",
    "indexee": "indexée",
    "indexes": "indexés",
    "indexe": "indexé",
    "Indexe": "Indexé",
    "synchronisee": "synchronisée",
    "synchronise": "synchronisé",
    "Synchronise": "Synchronisé",
    "desactive": "désactivé",
    "Desactive": "Désactivé",
    "desactiver": "désactiver",
    "lisibilite": "lisibilité",
    "defaut": "défaut",
    "Defaut": "Défaut",
    "regroupees": "regroupées",
    "regroupee": "regroupée",
    "regroupes": "regroupés",
    "regroupe": "regroupé",
    "Regroupe": "Regroupé",
    "detection": "détection",
    "Detection": "Détection",
    "ecran": "écran",
    "Ecran": "Écran",
    "ecrans": "écrans",
    "Probleme": "Problème",
    "probleme": "problème",
    "resolution": "résolution",
    "Resolution": "Résolution",
    "bientot": "bientôt",
    "Bientot": "Bientôt",
    "trouve": "trouvé",
    "Trouve": "Trouvé",
    "trouves": "trouvés",
    "trouvee": "trouvée",
    "trouvees": "trouvées",
    "recents": "récentes",
    "Recents": "Récentes",
    "recente": "récente",
    "recentes": "récentes",
    "Recent": "Récent",
    "recent": "récent",
    "restaure": "restauré",
    "Restaure": "Restauré",
    "partage": "partagé",
    "Verifier": "Vérifier",
    "verifier": "vérifier",
    "verifiez": "vérifiez",
    "Verifiez": "Vérifiez",
    "selectionnes": "sélectionnés",
    "supprimées": "supprimées",
    "supprimees": "supprimées",
    "deplacees": "déplacées",
    "deplacée": "déplacée",
    "deplacee": "déplacée",
    "generee": "générée",
    "generée": "générée",
    "numerique": "numérique",
    "Numerique": "Numérique",
    "categoríe": "catégorie",
    "categorie": "catégorie",
    "Categorie": "Catégorie",
    "categories": "catégories",
    "Categories": "Catégories",
    "reseau": "réseau",
    "Reseau": "Réseau",
    "reseaux": "réseaux",
    "hote": "hôte",
    "Hote": "Hôte",
    "deja": "déjà",
    "etre": "être",
    "oubliée": "oubliée",
    "oubliee": "oubliée",
    "oublie": "oublié",
    "Oublie": "Oublié",
    "echantillon": "échantillon",
    "Echantillon": "Échantillon",
    "derriere": "derrière",
    "Derriere": "Derrière",
    "premiere": "première",
    "Premiere": "Première",
    "premieres": "premières",
    "troisieme": "troisième",
    "Troisieme": "Troisième",
    "emoticone": "émoticône",
    "Emoticone": "Émoticône",
    "cle": "clé",
    "Cle": "Clé",
    "cles": "clés",
    "Cles": "Clés",
    "role": "rôle",
    "Role": "Rôle",
    "roles": "rôles",
    "hote": "hôte",
    "completement": "complètement",
    "Completement": "Complètement",
    "especes": "espèces",
    "espece": "espèce",
    "Espece": "Espèce",
    "heterogene": "hétérogène",
    "referentiel": "référentiel",
    "Referentiel": "Référentiel",
    "reference": "référence",
    "Reference": "Référence",
    "references": "références",
    "etait": "était",
    "Etait": "Était",
    "etaient": "étaient",
    "ete": "été",
    "Ete": "Été",
    "etre": "être",
    "evenements": "événements",
    "reponse": "réponse",
    "Reponse": "Réponse",
    "reponses": "réponses",
    "repete": "répété",
    "Repete": "Répété",
    "repeter": "répéter",
    "repetez": "répétez",
    "elimine": "éliminé",
    "Elimine": "Éliminé",
    "eliminer": "éliminer",
    "depot": "dépôt",
    "Depot": "Dépôt",
    "depots": "dépôts",
    "televerser": "téléverser",
    "Televerser": "Téléverser",
    "televerse": "téléversé",
    "compte": "compte",
    "comptee": "comptée",
    "comptees": "comptées",
    "comptes": "comptés",
    "editer": "éditer",
    "Editer": "Éditer",
    "edition": "édition",
    "Edition": "Édition",
    "edite": "édité",
    "Edite": "Édité",
    "veuillez": "veuillez",
    "Veuillez": "Veuillez",
    "echoue": "échoué",
    "reussi": "réussi",
    "Reussi": "Réussi",
    "reussie": "réussie",
    "reussites": "réussites",
    "demarrage": "démarrage",
    "Demarrage": "Démarrage",
    "arreter": "arrêter",
    "connexion": "connexion",
    "connecte": "connecté",
    "Connecte": "Connecté",
    "deconnecte": "déconnecté",
    "Deconnecte": "Déconnecté",
    "deconnecter": "déconnecter",
    "identifiant": "identifiant",
    "identifiants": "identifiants",
    "mot": "mot",
    "passe": "passe",
    "incorrect": "incorrect",
    "invalide": "invalide",
    "valide": "validé",
    "Valide": "Validé",
    "valider": "valider",
    "autorise": "autorisé",
    "Autorise": "Autorisé",
    "autoriser": "autoriser",
    "refuse": "refusé",
    "Refuse": "Refusé",
    "refusee": "refusée",
    "refusees": "refusées",
    "permission": "permission",
    "permissions": "permissions",
    "requise": "requise",
    "requis": "requis",
    "optionnel": "optionnel",
    "optionnelle": "optionnelle",
    "avance": "avancé",
    "Avance": "Avancé",
    "avancee": "avancée",
    "avancees": "avancées",
    "detail": "détail",
    "Detail": "Détail",
    "details": "détails",
    "Details": "Détails",
    "generique": "générique",
    "Generique": "Générique",
    "specifique": "spécifique",
    "Specifique": "Spécifique",
    "especifique": "spécifique",
    "propriete": "propriété",
    "Propriete": "Propriété",
    "proprietes": "propriétés",
    "capacite": "capacité",
    "Capacite": "Capacité",
    "capacites": "capacités",
    "activite": "activité",
    "Activite": "Activité",
    "activites": "activités",
    "priorite": "priorité",
    "Priorite": "Priorité",
    "priorites": "priorités",
    "securite": "sécurité",
    "Securite": "Sécurité",
    "confidentialite": "confidentialité",
    "Confidentialite": "Confidentialité",
    "confidentialite": "confidentialité",
    "legal": "légal",
    "Legal": "Légal",
    "legales": "légales",
    "legale": "légale",
    "mentions": "mentions",
    "obligatoire": "obligatoire",
    "facultatif": "facultatif",
    "facultative": "facultative",
    "personnalise": "personnalisé",
    "Personnalise": "Personnalisé",
    "personnalisee": "personnalisée",
    "personnalisees": "personnalisées",
    "personnaliser": "personnaliser",
    "apparaitre": "apparaître",
    "disparaitre": "disparaître",
    "disparait": "disparaît",
    "connaitre": "connaître",
    "connait": "connaît",
    "paraitre": "paraître",
    "parait": "paraît",
    "interet": "intérêt",
    "Interet": "Intérêt",
    "interessant": "intéressant",
    "Interessant": "Intéressant",
    "interest": "intérêt",
    "exterieur": "extérieur",
    "Exterieur": "Extérieur",
    "exterieure": "extérieure",
    "interieur": "intérieur",
    "Interieur": "Intérieur",
    "interieure": "intérieure",
    "deroulement": "déroulement",
    "Deroulement": "Déroulement",
    "deroule": "déroulé",
    "derouler": "dérouler",
    "enquete": "enquête",
    "Enquete": "Enquête",
    "enquetes": "enquêtes",
    "etiquette": "étiquette",
    "Etiquette": "Étiquette",
    "etiquettes": "étiquettes",
    "etiqueter": "étiqueter",
    "etiquete": "étiqueté",
    "repertoire": "répertoire",
    "Repertoire": "Répertoire",
    "repertoires": "répertoires",
    "suppression": "suppression",
    "supprimer": "supprimer",
    "restauration": "restauration",
    "restaurer": "restaurer",
    "compression": "compression",
    "compresser": "compresser",
    "compresse": "compressé",
    "Compresse": "Compressé",
    "compressee": "compressée",
    "compressees": "compressées",
    "decompression": "décompression",
    "Decompression": "Décompression",
    "decompresse": "décompressé",
    "duplique": "dupliqué",
    "Duplique": "Dupliqué",
    "dupliquees": "dupliquées",
    "dupliquees": "dupliquées",
    "dupliquees": "dupliquées",
    "duplique": "dupliqué",
    "dupliquees": "dupliquées",
    "similaires": "similaires",
    "similaire": "similaire",
    "faible": "faible",
    "eleve": "élevé",
    "Eleve": "Élevé",
    "elevee": "élevée",
    "elevees": "élevées",
    "eleves": "élevés",
    "statistiques": "statistiques",
    "Statistiques": "Statistiques",
    "voyage": "voyage",
    "voyages": "voyages",
    "organisation": "organisation",
    "Organiser": "Organiser",
    "organiser": "organiser",
    "organise": "organisé",
    "Organise": "Organisé",
    "organisee": "organisée",
    "organisees": "organisées",
    "automatique": "automatique",
    "automatiquement": "automatiquement",
    "manuelle": "manuelle",
    "manuel": "manuel",
    "manuellement": "manuellement",
    "progresssion": "progression",
    "progression": "progression",
    "pourcentage": "pourcentage",
    "octets": "octets",
    "megaoctets": "mégaoctets",
    "Megaoctets": "Mégaoctets",
    "gigaoctets": "gigaoctets",
    "ko": "Ko",
    "mo": "Mo",
    "go": "Go",
}

PHRASE_FIXES = [
    ("mis a jour", "mis à jour"),
    ("a jour", "à jour"),
    ("a la ", "à la "),
    ("a l'", "à l'"),
    ("a tout", "à tout"),
    ("a vos", "à vos"),
    ("a votre", "à votre"),
    ("a un ", "à un "),
    ("a une ", "à une "),
    ("a des ", "à des "),
    ("a ce ", "à ce "),
    ("a cette ", "à cette "),
    ("a ces ", "à ces "),
    ("a partir", "à partir"),
    ("a nouveau", "à nouveau"),
    ("a utiliser", "à utiliser"),
    ("a analyser", "à analyser"),
    ("a synchroniser", "à synchroniser"),
    ("a restaurer", "à restaurer"),
    ("a supprimer", "à supprimer"),
    ("a deplacer", "à déplacer"),
    ("a charger", "à charger"),
    ("a faire", "à faire"),
    ("a venir", "à venir"),
    ("a tous", "à tous"),
    ("a toutes", "à toutes"),
    ("a chaque", "à chaque"),
    ("a moins", "à moins"),
    ("a cause", "à cause"),
    ("a cote", "à côté"),
    ("a côté", "à côté"),
    # Trailing space / boundary so "acces au" is not mangled into "accès àu".
    ("Acces a ", "Accès à "),
    ("acces a ", "accès à "),
    ("d'acceder a ", "d'accéder à "),
    ("d'accéder a ", "d'accéder à "),
    ("l'acces a ", "l'accès à "),
    ("l'accès a ", "l'accès à "),
    ("accès àu", "accès au"),
    ("A propos", "À propos"),
    ("limite active", "limité activé"),
    ("photo limite", "photo limité"),
    ("Limite de taille", "Limite de taille"),
    ("taille limite", "taille limite"),
    ("espace economise", "espace économisé"),
    ("Espace economise", "Espace économisé"),
]

MANUAL = {
    "settingsCacheSizeLimit": "Limite de taille du cache",
    "settingsCacheSizeLimitDescription": (
        "Stockage maximal utilisé par les miniatures et fichiers temporaires."
    ),
    "navDiscover": "Découvrir",
    "navLockedAlbums": "Albums verrouillés",
    "navSettings": "Paramètres",
    "settingsTitle": "Paramètres",
    "settingsSectionAbout": "À propos",
    "settingsLanguageSystem": "Langue du système",
    "settingsLanguageFrench": "Français",
    "settingsTheme": "Thème",
    "actionReset": "Réinitialiser",
    "actionUnlock": "Déverrouiller",
    "actionOpenSettings": "Ouvrir les paramètres",
    "valueNotSet": "Non défini",
    "errorMediaNotFound": "Média introuvable",
    "themeSystemDefault": "Système",
    "settingsAutoClearOnClose": "Effacer à la fermeture",
    "settingsAutoClearOnCloseSubtitle": (
        "Effacer le cache lorsque l'application est fermée"
    ),
    "settingsOrganizeGestures": "Gestes d'organisation",
    "settingsPrivacyPolicy": "Politique de confidentialité",
}


def fix_string(value: str) -> str:
    placeholders: dict[str, str] = {}

    def _save(match: re.Match[str]) -> str:
        key = f"\ue000{len(placeholders)}\ue001"
        placeholders[key] = match.group(0)
        return key

    tmp = re.sub(r"\{[^}]+\}", _save, value)
    keys = sorted(WORD_MAP.keys(), key=len, reverse=True)
    pattern = re.compile(r"(?<![A-Za-zÀ-ÿ])(" + "|".join(map(re.escape, keys)) + r")(?![A-Za-zÀ-ÿ])")
    tmp = pattern.sub(lambda m: WORD_MAP[m.group(0)], tmp)
    for src, dst in PHRASE_FIXES:
        tmp = tmp.replace(src, dst)
    for key, original in placeholders.items():
        tmp = tmp.replace(key, original)
    return tmp


def main() -> None:
    data = json.loads(ARB.read_text(encoding="utf-8"))
    changed = 0
    for key, value in list(data.items()):
        if key.startswith("@") or not isinstance(value, str):
            continue
        fixed = fix_string(value)
        if fixed != value:
            data[key] = fixed
            changed += 1
    for key, value in MANUAL.items():
        if key in data and data[key] != value:
            data[key] = value
            changed += 1

    # Preserve key order from the original parse (Py3.7+ dict order).
    out = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    ARB.write_text(out, encoding="utf-8", newline="\n")
    print(f"updated_values={changed}")
    print(f"non_ascii={sum(1 for ch in out if ord(ch) > 127)}")
    for sample in (
        "actionReset",
        "navSettings",
        "settingsLanguageFrench",
        "settingsSectionAbout",
        "organizeMoveFailed",
        "settingsCacheSizeLimit",
    ):
        print(f"{sample} => {data.get(sample)}")


if __name__ == "__main__":
    main()
